'use strict';

module.exports = {
  auth: require('./auth'),
  user: require('./user'),
  activity: require('./activity'),
  category: require('./category'),
  location: require('./location'),
  sublocation: require('./sublocation'),
  startinglocation: require('./startinglocation'),
  tag: require('./tag'),
  service: require('./service'),
  equipment: require('./equipment'),
  facility: require('./facility'),
  welcome: require('./welcome'),
  accommodation: require('./accommodation'),
  currency: require('./currency'),
  trip: require('./trip'),
  review: require('./review'),
  poi: require('./poi'),
  pressRelease: require('./pressRelease'),
  media: require('./media'),
  season: require('./season'),
  seasonalEvents: require('./seasonalEvents'),
  booking: require('./booking'),
  events: require('./events'),
  bus: require('./bus'),
  cities: require('./cities'),
  transport: require('./transport'),
  airline: require('./airline'),
  hotel: require('./hotel'),
  languages: require('./languages'),
  plans: require('./plans'),
  news: require('./news'),
  userPermissions: require('./userPermissions'),
  payment: require('./payment'),
  easyAdd: require('./easyAdd')
};
